name: release

on:
  push:
    tags:
      - 'v*'
env:
  IMAGE_NAME: ${{ github.event.repository.name }}

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download release notes utility
        env:
          GH_REL_URL: https://github.com/buchanae/github-release-notes/releases/download/0.2.0/github-release-notes-linux-amd64-0.2.0.tar.gz
        run: cd /tmp && curl -sSL ${GH_REL_URL} | tar xz && sudo mv github-release-notes /usr/local/bin/

      - name: Generate release notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo 'CHANGELOG' > /tmp/release.txt
          github-release-notes -org mmorejon -repo erase-una-vez-2 -since-latest-release >> /tmp/release.txt

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          bodyFile: "/tmp/release.txt"
          token: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: mmorejon
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          file: ./Dockerfile
          tags: |
            mmorejon/${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}
            ghcr.io/mmorejon/${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}